from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Sequence

import numpy as np

try:  # scipy is available in the project environment; keep a graceful fallback.
    from scipy.optimize import minimize
except Exception:  # pragma: no cover
    minimize = None

from model.control_types import ActuatorCommand, FeedObservation, FurnaceObservation, MPCDecision
from model.preheater_forward_model import PreheaterForwardModel
from model.furnace_dynamic import FurnaceDyn
from model.actuator_dynamic import ActuatorDynamic, ActuatorDynamicConfig
from model.resource_model import ResourceModel, ResourceState
from model.feed_preview import FeedPreviewProvider, ConstantFeedPreview
from model.model_types import ResourceBoundary
from model.thermal_core import power_kW


@dataclass
class NMPCConfig:
    """Control-blocking nonlinear MPC configuration."""

    dt_pred_s: float = 20.0
    # Internal integration step used inside each prediction interval.  The
    # decision/update grid can remain coarse (dt_pred_s), but the distributed
    # preheater model is sensitive to very large integration steps.  A smaller
    # rollout step keeps NMPC predictions close to the plant without increasing
    # the number of optimization variables.
    rollout_dt_s: float = 5.0
    horizon_s: float = 600.0
    block_edges_s: tuple[float, ...] = (0.0, 120.0, 300.0, 480.0, 600.0)
    reoptimize_s: float = 20.0

    T_set_C: float = 872.99
    omega_ref: float = 0.3218

    T_ref_low_C: float = 850.0
    T_ref_high_C: float = 895.99
    T_safe_low_C: float = 850.0
    T_safe_high_C: float = 1100.0

    Tg_min_C: float = 100.0
    Tg_max_C: float = 930.0
    vg_min_mps: float = 3.0
    vg_max_mps: float = 12.0

    nominal_Tg_C: float = 800.0
    nominal_vg_mps: float = 12.0

    q_Tavg: float = 1.0
    q_ref_band: float = 8.0
    q_safe_band: float = 250.0
    q_terminal_Tavg: float = 5.0
    q_omega: float = 80.0
    r_energy: float = 1.0e-4
    r_aux_heat: float = 1.5e-4
    r_nominal_Tg: float = 2.0e-5
    # Do not penalize around nominal_vg=12; that would encourage high flow.
    r_nominal_vg: float = 0.0
    r_delta_Tg: float = 8.0e-5
    r_delta_vg: float = 0.08

    # Economic operation: high v_g remains available for emergency recovery,
    # but reference-band operation should prefer lower circulation/flow.
    economic_vg_mps: float = 8.0
    high_vg_threshold_mps: float = 8.5
    r_economic_vg: float = 0.04
    r_high_vg: float = 1.2
    r_fan_power: float = 0.35
    r_aux_flow: float = 8.0
    ref_band_economy_multiplier: float = 6.0

    max_Tg_slew_C_per_s: float = 20.0
    max_vg_slew_mps_per_s: float = 0.4
    actuator_tau_Tg_s: float = 3.0
    actuator_tau_vg_s: float = 1.0

    maxiter: int = 35
    ftol: float = 1.0e-3
    fallback_on_fail: bool = True


class NonlinearMPCController:
    """Control-blocking NMPC using the complete distributed preheater rollout.

    Main decisions are generated by optimizing a future Tg/vg sequence and
    evaluating it on the full 20-cell preheater + furnace model.  Feed preview,
    dynamic stack resources, auxiliary heat accounting, and first-order actuator
    dynamics are included in the prediction path.
    """

    def __init__(self, cfg: NMPCConfig | None = None, fallback_controller=None, resource_model: ResourceModel | None = None):
        self.cfg = cfg or NMPCConfig()
        self.fallback_controller = fallback_controller
        self.resource_model = resource_model or ResourceModel()
        self.prev_Tg_ref_C = float(self.cfg.nominal_Tg_C)
        self.prev_vg_ref_mps = float(self.cfg.nominal_vg_mps)
        self.prev_solution: np.ndarray | None = None
        self.plan_start_s: float | None = None
        self.next_reopt_s: float = -math.inf
        self.last_decision: MPCDecision | None = None

    @property
    def n_blocks(self) -> int:
        return max(1, len(self.cfg.block_edges_s) - 1)

    def initialize(self, *, Tg_ref_C: float, vg_ref_mps: float, time_s: float = 0.0) -> None:
        self.prev_Tg_ref_C = float(Tg_ref_C)
        self.prev_vg_ref_mps = float(vg_ref_mps)
        z = []
        for _ in range(self.n_blocks):
            z.extend([self.prev_Tg_ref_C, self.prev_vg_ref_mps])
        self.prev_solution = np.asarray(z, dtype=float)
        self.plan_start_s = float(time_s)
        self.next_reopt_s = float(time_s)

    def _bounds(self, resource: ResourceBoundary):
        # Temperature bound is the effective cap. Natural stack temperature may be
        # lower, in which case auxiliary heat is charged in rollout/execution.
        Tg_hi = min(float(resource.T_stack_cap_C), self.cfg.Tg_max_C)
        vg_hi = min(float(resource.v_stack_cap_mps), self.cfg.vg_max_mps)
        b = []
        for _ in range(self.n_blocks):
            b.append((self.cfg.Tg_min_C, max(self.cfg.Tg_min_C, Tg_hi)))
            b.append((self.cfg.vg_min_mps, max(self.cfg.vg_min_mps, vg_hi)))
        return b

    def _clip_z(self, z: Sequence[float], resource: ResourceBoundary) -> np.ndarray:
        bounds = self._bounds(resource)
        zz = np.asarray(z, dtype=float).copy()
        for i, (lo, hi) in enumerate(bounds):
            zz[i] = float(np.clip(zz[i], lo, hi))
        return zz

    def _block_index(self, elapsed_s: float) -> int:
        edges = self.cfg.block_edges_s
        for i in range(len(edges) - 1):
            if edges[i] <= elapsed_s < edges[i + 1] - 1e-12:
                return i
        return self.n_blocks - 1

    def _control_from_z(self, z: Sequence[float], elapsed_s: float) -> tuple[float, float]:
        j = self._block_index(elapsed_s)
        return float(z[2 * j]), float(z[2 * j + 1])

    def _initial_guess_pool(self, obs: FurnaceObservation, resource: ResourceBoundary, prev_cmd: ActuatorCommand | None):
        pool: list[np.ndarray] = []
        if self.prev_solution is not None:
            old = self._clip_z(self.prev_solution, resource)
            shifted = old.copy()
            if self.n_blocks > 1:
                shifted[:-2] = old[2:]
                shifted[-2:] = old[-2:]
            pool.append(shifted)

        def const_seq(Tg, vg):
            z = []
            for _ in range(self.n_blocks):
                z.extend([Tg, vg])
            return self._clip_z(z, resource)

        pool.append(const_seq(self.cfg.nominal_Tg_C, self.cfg.nominal_vg_mps))
        if prev_cmd is not None:
            pool.append(const_seq(prev_cmd.Tg_cmd_C, prev_cmd.vg_cmd_mps))

        err = self.cfg.T_set_C - obs.T_avg_C
        if err > 20.0:
            pool.append(const_seq(resource.T_stack_cap_C, self.cfg.vg_max_mps))
            pool.append(const_seq(900.0, self.cfg.vg_max_mps))
        elif err < -20.0:
            pool.append(const_seq(600.0, 6.0))
            pool.append(const_seq(500.0, 3.0))

        if err > 10.0 and self.n_blocks >= 2:
            z = const_seq(self.cfg.nominal_Tg_C, self.cfg.nominal_vg_mps)
            z[0] = min(resource.T_stack_cap_C, self.cfg.Tg_max_C)
            z[1] = min(resource.v_stack_cap_mps, self.cfg.vg_max_mps)
            pool.append(z)
        if err < -10.0 and self.n_blocks >= 2:
            z = const_seq(self.cfg.nominal_Tg_C, self.cfg.nominal_vg_mps)
            z[0] = 500.0
            z[1] = 3.0
            pool.append(z)
        return pool

    def _make_actuator_prediction(self, prev_cmd: ActuatorCommand | None) -> ActuatorDynamic:
        act = ActuatorDynamic(
            ActuatorDynamicConfig(
                tau_Tg_s=self.cfg.actuator_tau_Tg_s,
                tau_vg_s=self.cfg.actuator_tau_vg_s,
                max_dTg_C_per_s=self.cfg.max_Tg_slew_C_per_s,
                max_dvg_mps_per_s=self.cfg.max_vg_slew_mps_per_s,
                Tg_min_C=self.cfg.Tg_min_C,
                Tg_max_C=self.cfg.Tg_max_C,
                vg_min_mps=self.cfg.vg_min_mps,
                vg_max_mps=self.cfg.vg_max_mps,
            ),
            opt_cfg=preheater_opt_cfg_placeholder(),
        )
        # Rebind opt_cfg below by direct assignment in rollout, where preheater exists.
        if prev_cmd is not None:
            act.initialize(prev_cmd.Tg_cmd_C, prev_cmd.vg_cmd_mps)
        else:
            act.initialize(self.prev_Tg_ref_C, self.prev_vg_ref_mps)
        return act

    def _feed_sequence(self, feed: FeedObservation, feed_preview: FeedPreviewProvider | None, *, dt_s: float) -> list[FeedObservation]:
        provider = feed_preview or ConstantFeedPreview(feed.composition, feed.normalize)
        return provider.get(feed.time_s, horizon_s=self.cfg.horizon_s, dt_s=dt_s)

    def _rollout_cost(self, z: Sequence[float], *, preheater: PreheaterForwardModel, furnace: FurnaceDyn,
                      feed: FeedObservation, obs: FurnaceObservation, resource: ResourceBoundary,
                      prev_cmd: ActuatorCommand | None, disturbance=None,
                      feed_preview: FeedPreviewProvider | None = None) -> tuple[float, float, float, float, float, float]:
        z = self._clip_z(z, resource)
        p = preheater.clone()
        f = furnace.clone()
        rollout_dt = min(max(float(self.cfg.rollout_dt_s), 1e-6), max(float(self.cfg.dt_pred_s), 1e-6))
        steps = max(1, int(math.ceil(self.cfg.horizon_s / rollout_dt)))
        feeds = self._feed_sequence(feed, feed_preview, dt_s=rollout_dt)
        cost = 0.0
        pred_T = obs.T_avg_C
        pred_stack = obs.T_stack_C
        pred_vstack = obs.v_stack_mps
        pred_w = preheater.state().omega_out
        max_T = -1e9
        min_T = 1e9
        aux_total = 0.0

        act = ActuatorDynamic(
            ActuatorDynamicConfig(
                tau_Tg_s=self.cfg.actuator_tau_Tg_s,
                tau_vg_s=self.cfg.actuator_tau_vg_s,
                max_dTg_C_per_s=self.cfg.max_Tg_slew_C_per_s,
                max_dvg_mps_per_s=self.cfg.max_vg_slew_mps_per_s,
                Tg_min_C=self.cfg.Tg_min_C,
                Tg_max_C=self.cfg.Tg_max_C,
                vg_min_mps=self.cfg.vg_min_mps,
                vg_max_mps=self.cfg.vg_max_mps,
            ),
            opt_cfg=p.opt_cfg,
        )
        if prev_cmd is not None:
            act.initialize(prev_cmd.Tg_cmd_C, prev_cmd.vg_cmd_mps)
        else:
            act.initialize(self.prev_Tg_ref_C, self.prev_vg_ref_mps)

        for k in range(steps):
            elapsed = k * rollout_dt
            dt_step = min(rollout_dt, max(self.cfg.horizon_s - elapsed, 1e-9))
            Tg_ref, vg_ref = self._control_from_z(z, elapsed)
            res_state: ResourceState = self.resource_model.from_observation(
                FurnaceObservation(time_s=obs.time_s + elapsed, T_avg_C=pred_T, T_stack_C=pred_stack, v_stack_mps=pred_vstack)
            )
            Tg_eff, vg_eff, applied = act.step(
                Tg_ref,
                vg_ref,
                dt_step,
                T_stack_available_C=res_state.T_stack_available_C,
                v_stack_available_mps=res_state.v_stack_available_mps,
                mdot_stack_cap_kgps=res_state.mdot_stack_available_kgps,
            )
            aux_total += applied.Q_aux_heat_kW * dt_step
            ff = feeds[min(k, len(feeds) - 1)]
            st = p.step(ff, Tg_eff, vg_eff, dt_step)
            pred_w = st.omega_out
            pred_T, pred_stack, pred_vstack = f.step(pred_w, dt_s=dt_step, disturbance=disturbance)
            max_T = max(max_T, pred_T)
            min_T = min(min_T, pred_T)

            eT = pred_T - self.cfg.T_set_C
            ref_hi = max(pred_T - self.cfg.T_ref_high_C, 0.0)
            ref_lo = max(self.cfg.T_ref_low_C - pred_T, 0.0)
            safe_hi = max(pred_T - self.cfg.T_safe_high_C, 0.0)
            safe_lo = max(self.cfg.T_safe_low_C - pred_T, 0.0)
            ew = pred_w - self.cfg.omega_ref
            try:
                energy = power_kW(Tg_eff, vg_eff, p.opt_cfg)
            except Exception:
                energy = 0.0

            in_ref_band = (ref_hi <= 1e-12 and ref_lo <= 1e-12)
            economy_mult = self.cfg.ref_band_economy_multiplier if in_ref_band else 1.0
            high_v_excess = max(vg_eff - self.cfg.high_vg_threshold_mps, 0.0)
            economic_v_error = max(vg_eff - self.cfg.economic_vg_mps, 0.0)
            economic_cost = (
                self.cfg.r_energy * energy
                + self.cfg.r_fan_power * applied.fan_circulation_power_kW
                + self.cfg.r_high_vg * high_v_excess * high_v_excess
                + self.cfg.r_economic_vg * economic_v_error * economic_v_error
                + self.cfg.r_aux_flow * applied.mdot_aux_flow_kgps * applied.mdot_aux_flow_kgps
                + self.cfg.r_aux_heat * applied.Q_aux_heat_kW * applied.Q_aux_heat_kW
            )
            stage_cost = (
                self.cfg.q_Tavg * eT * eT
                + self.cfg.q_ref_band * (ref_hi * ref_hi + ref_lo * ref_lo)
                + self.cfg.q_safe_band * (safe_hi * safe_hi + safe_lo * safe_lo)
                + self.cfg.q_omega * ew * ew
                + economy_mult * economic_cost
            )
            # Keep the objective scale comparable when rollout_dt_s is smaller
            # than dt_pred_s.  Otherwise simply refining the integration grid
            # would multiply the stage cost and change tuning semantics.
            cost += stage_cost * (dt_step / max(self.cfg.dt_pred_s, 1e-9))

        terminal = pred_T - self.cfg.T_set_C
        cost += self.cfg.q_terminal_Tavg * terminal * terminal

        last_Tg = self.prev_Tg_ref_C
        last_vg = self.prev_vg_ref_mps
        for j in range(self.n_blocks):
            Tg = float(z[2 * j]); vg = float(z[2 * j + 1])
            cost += self.cfg.r_nominal_Tg * (Tg - self.cfg.nominal_Tg_C) ** 2
            cost += self.cfg.r_nominal_vg * (vg - self.cfg.nominal_vg_mps) ** 2
            cost += self.cfg.r_economic_vg * max(vg - self.cfg.economic_vg_mps, 0.0) ** 2
            cost += self.cfg.r_high_vg * max(vg - self.cfg.high_vg_threshold_mps, 0.0) ** 2
            cost += self.cfg.r_delta_Tg * (Tg - last_Tg) ** 2
            cost += self.cfg.r_delta_vg * (vg - last_vg) ** 2
            last_Tg, last_vg = Tg, vg

        return float(cost), float(pred_T), float(pred_w), float(min_T), float(max_T), float(aux_total)

    def _fallback(self, *, obs, preheater, furnace, feed, resource, disturbance, feed_preview=None) -> MPCDecision:
        if self.fallback_controller is not None and self.cfg.fallback_on_fail:
            return self.fallback_controller.step(
                obs=obs,
                preheater=preheater,
                furnace=furnace,
                feed=feed,
                resource=resource,
                disturbance=disturbance,
            )
        return MPCDecision(
            time_s=obs.time_s,
            Tg_ref_C=self.cfg.nominal_Tg_C,
            vg_ref_mps=self.cfg.nominal_vg_mps,
            omega_target=self.cfg.omega_ref,
            omega_reachable=preheater.state().omega_out,
            predicted_Tavg_C=obs.T_avg_C,
            predicted_omega_out=preheater.state().omega_out,
            cost=float('inf'),
            feasible=False,
            source='nmpc_fallback_nominal',
            note='NMPC unavailable; nominal fallback',
        )

    def _planned_decision(self, obs: FurnaceObservation, preheater: PreheaterForwardModel) -> MPCDecision | None:
        if self.prev_solution is None or self.plan_start_s is None:
            return None
        elapsed = max(0.0, obs.time_s - self.plan_start_s)
        if elapsed > self.cfg.horizon_s:
            return None
        Tg, vg = self._control_from_z(self.prev_solution, elapsed)
        last = self.last_decision
        return MPCDecision(
            time_s=obs.time_s,
            Tg_ref_C=Tg,
            vg_ref_mps=vg,
            omega_target=self.cfg.omega_ref,
            omega_reachable=preheater.state().omega_out,
            predicted_Tavg_C=(last.predicted_Tavg_C if last is not None else obs.T_avg_C),
            predicted_omega_out=(last.predicted_omega_out if last is not None else preheater.state().omega_out),
            cost=(last.cost if last is not None else 0.0),
            feasible=True,
            source='nmpc_plan_hold',
            note='Using cached NMPC plan between re-optimizations',
        )

    def step(self, *, obs: FurnaceObservation, preheater: PreheaterForwardModel, furnace: FurnaceDyn,
             feed: FeedObservation, resource: ResourceBoundary, prev_cmd: ActuatorCommand | None = None,
             disturbance=None, feed_preview: FeedPreviewProvider | None = None) -> MPCDecision:
        if obs.time_s + 1e-9 < self.next_reopt_s:
            planned = self._planned_decision(obs, preheater)
            if planned is not None:
                return planned

        if minimize is None:
            dec = self._fallback(obs=obs, preheater=preheater, furnace=furnace, feed=feed, resource=resource,
                                 disturbance=disturbance, feed_preview=feed_preview)
            self.last_decision = dec
            return dec

        pool = self._initial_guess_pool(obs, resource, prev_cmd)
        seed_scores = []
        for z0 in pool:
            seed_scores.append((self._rollout_cost(z0, preheater=preheater, furnace=furnace, feed=feed,
                                                   obs=obs, resource=resource, prev_cmd=prev_cmd,
                                                   disturbance=disturbance, feed_preview=feed_preview)[0], z0))
        z0 = min(seed_scores, key=lambda x: x[0])[1]

        def obj(z):
            val = self._rollout_cost(z, preheater=preheater, furnace=furnace, feed=feed,
                                     obs=obs, resource=resource, prev_cmd=prev_cmd,
                                     disturbance=disturbance, feed_preview=feed_preview)[0]
            if not np.isfinite(val):
                return 1e30
            return val

        try:
            res = minimize(
                obj,
                z0,
                method='SLSQP',
                bounds=self._bounds(resource),
                options={'maxiter': self.cfg.maxiter, 'ftol': self.cfg.ftol, 'disp': False},
            )
        except Exception as exc:
            dec = self._fallback(obs=obs, preheater=preheater, furnace=furnace, feed=feed, resource=resource,
                                 disturbance=disturbance, feed_preview=feed_preview)
            self.last_decision = dec
            return MPCDecision(**{**dec.__dict__, 'source': dec.source + '_exception', 'note': str(exc)})

        z_best = self._clip_z(res.x if getattr(res, 'x', None) is not None else z0, resource)
        cost, pred_T, pred_w, min_T, max_T, aux_total = self._rollout_cost(
            z_best,
            preheater=preheater,
            furnace=furnace,
            feed=feed,
            obs=obs,
            resource=resource,
            prev_cmd=prev_cmd,
            disturbance=disturbance,
            feed_preview=feed_preview,
        )
        if not np.isfinite(cost):
            dec = self._fallback(obs=obs, preheater=preheater, furnace=furnace, feed=feed, resource=resource,
                                 disturbance=disturbance, feed_preview=feed_preview)
            self.last_decision = dec
            return dec

        self.prev_solution = z_best
        self.plan_start_s = float(obs.time_s)
        self.next_reopt_s = float(obs.time_s + self.cfg.reoptimize_s)
        Tg_ref, vg_ref = self._control_from_z(z_best, 0.0)
        self.prev_Tg_ref_C = float(Tg_ref)
        self.prev_vg_ref_mps = float(vg_ref)
        feasible = bool(getattr(res, 'success', True))
        dec = MPCDecision(
            time_s=obs.time_s,
            Tg_ref_C=float(Tg_ref),
            vg_ref_mps=float(vg_ref),
            omega_target=self.cfg.omega_ref,
            omega_reachable=float(pred_w),
            predicted_Tavg_C=float(pred_T),
            predicted_omega_out=float(pred_w),
            cost=float(cost),
            feasible=feasible,
            source='nmpc_block_slsqp',
            note=(f'blocks={self.n_blocks}; rollout_dt={self.cfg.rollout_dt_s:g}s; success={getattr(res, "success", True)}; '
                  f'minT={min_T:.2f}; maxT={max_T:.2f}; aux_kJ={aux_total:.1f}; '
                  f'msg={getattr(res, "message", "")}'[:200]),
        )
        self.last_decision = dec
        return dec


def preheater_opt_cfg_placeholder():
    # Keeps type checkers happy; actual rollout actuator objects are rebound to
    # the cloned preheater's Config.  This function avoids importing Config at
    # module top just for a default object.
    from model.model_types import Config
    return Config()
